name: ansible-lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ansible Lint
        uses: ansible/ansible-lint-action@v6.8.2
